services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    container_name: backend
    restart: always
    environment:
      - FLASK_ENV=development
      #- HUGGINGFACEHUB_API_TOKEN=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
      #- HUGGINGFACE_HUB_CACHE=/app/.cache/huggingface
    expose:
      - 7000
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: frontend
    restart: always
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
