services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    container_name: backend
    restart: always
    environment:
      - FLASK_ENV=development
    ports:
      - "7000:7000"  # 호스트:컨테이너 포트 매핑
    expose:
      - 7000
    networks:
      - app-network

  ai:
    build: ./ai
    volumes:
      - ./ai:/workspace
    container_name: ai
    restart: always
    environment:
      - FLASK_ENV=development
    expose:
      - "7777:7777"
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # 사용 가능한 모든 GPU를 사용합니다.
              capabilities: [gpu]  # GPU 사용을 지정합니다

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: frontend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
      - ai
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
